-   repo: git://github.com/pre-commit/pre-commit-hooks
    rev: v0.7.1
    hooks:
    -   id: check-merge-conflict
    -   id: trailing-whitespace
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: debug-statements
        language_version: python3.7
    -   id: check-added-large-files
    -   id: double-quote-string-fixer
-   repo: https://github.com/asottile/reorder_python_imports.git
    rev: v0.3.1
    hooks:
    -   id: reorder-python-imports
        language_version: python3.7
-   repo: git://github.com/pre-commit/mirrors-pylint
    rev: v2.3.1
    hooks:
    -   id: pylint
        args:
        - --rcfile=.pylintrc
        - -rn
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.720
    hooks:
    -   id: mypy
        args: [--ignore-missing-imports, --no-strict-optional]
