repos:
-   repo: https://github.com/asottile/reorder_python_imports.git
    rev: v1.7.0
    hooks:
    - id: reorder-python-imports
      language_version: python3.7

-   repo: https://github.com/asottile/yesqa
    rev: v0.0.11
    hooks:
    -   id: yesqa

-   repo: git://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: check-added-large-files
    -   id: check-ast
    -   id: check-byte-order-marker
    -   id: check-docstring-first
    -   id: check-json
    -   id: check-merge-conflict
    -   id: check-xml
    -   id: check-yaml
    -   id: debug-statements
    -   id: detect-aws-credentials
    -   id: detect-private-key
    -   id: double-quote-string-fixer
    -   id: end-of-file-fixer
    -   id: forbid-new-submodules
    -   id: pretty-format-json
        args: [--autofix]
    -   id: requirements-txt-fixer
    -   id: sort-simple-yaml
    -   id: trailing-whitespace

-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.720
    hooks:
    -   id: mypy
        args: [--ignore-missing-imports]

-   repo: git://github.com/pre-commit/mirrors-pylint
    rev: v2.3.1
    hooks:
        - id: pylint
          args:
          - --rcfile=.pylintrc
          - -rn

-   repo: git://github.com/pre-commit/pygrep-hooks
    rev: v1.4.1
    hooks:
    -   id: python-check-blanket-noqa
    -   id: python-check-mock-methods
    -   id: python-no-eval
    -   id: python-no-log-warn
    -   id: python-use-type-annotations
