repos:
-   repo: https://github.com/psf/black
    rev: 19.3b0
    hooks:
    - id: black
      language_version: python3.6

-   repo: https://github.com/asottile/blacken-docs
    rev: v1.3.0
    hooks:
    -   id: blacken-docs

-   repo: https://github.com/asottile/reorder_python_imports.git
    rev: v1.7.0
    hooks:
    - id: reorder-python-imports
      language_version: python3.6
      args:
       - --application-directories=./back

-   repo: https://github.com/asottile/yesqa
    rev: v0.0.11
    hooks:
    -   id: yesqa

- repo: https://github.com/pryorda/dockerfilelint-precommit-hooks
  rev: v0.1.0
  hooks:
  - id: dockerfilelint
    stages: [commit]

-   repo: git://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: check-added-large-files
    -   id: check-byte-order-marker
    -   id: check-json
    -   id: check-merge-conflict
    -   id: check-toml
    -   id: check-xml
    -   id: check-yaml
    -   id: debug-statements
        language_version: python3.6
    -   id: detect-private-key
    -   id: end-of-file-fixer
    -   id: fix-encoding-pragma
        args: [--remove]
    -   id: forbid-new-submodules
    # -   id: no-commit-to-branch
    #     args: [--branch, master]
    -   id: pretty-format-json
        args: [--autofix]
    -   id: requirements-txt-fixer
    -   id: sort-simple-yaml
    -   id: trailing-whitespace

-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.720
    hooks:
    -   id: mypy
        args: [--ignore-missing-imports]

-   repo: git://github.com/pre-commit/mirrors-pylint
    rev: v2.3.1
    hooks:
        - id: pylint
          args:
          - --rcfile=.pylintrc
          - -rn

-   repo: https://github.com/Lucas-C/pre-commit-hooks-safety
    sha: v1.1.0
    hooks:
    -   id: python-safety-dependencies-check

-   repo: git://github.com/pre-commit/pygrep-hooks
    rev: v1.4.1
    hooks:
    -   id: python-check-blanket-noqa
    -   id: python-check-mock-methods
    -   id: python-no-eval
    -   id: python-no-log-warn
    -   id: python-use-type-annotations
    -   id: rst-backticks
